package org.khana.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Restaurant")
public class Restaurant {
    private String restId;
    private String restName;
    private String itemName;
    private String upiId;
    private String desc;

    public Restaurant() {
    }

    @DynamoDBHashKey(attributeName = "RestaurantId")
    @DynamoDBAutoGeneratedKey
    public String getRestId() {
        return restId;
    }

    public void setRestId(String restId) {
        this.restId = restId;
    }

    @DynamoDBAttribute(attributeName="RestaurantName")
    public String getRestName() {
        return restName;
    }

    public void setRestName(String restName) {
        this.restName = restName;
    }

    @DynamoDBAttribute(attributeName="UpiId")
    public String getUpiId() {
        return upiId;
    }

    public void setUpiId(String upiId) {
        this.upiId = upiId;
    }

    @DynamoDBAttribute(attributeName="RestaurantDescription")
    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    @DynamoDBAttribute(attributeName="ItemName")
    public String getItemName() {
        return itemName;
    }

    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    @Override
    public String toString() {
        return "Menu{" +
                "restId='" + restId + '\'' +
                ", restName='" + restName + '\'' +
                ", itemName='" + itemName + '\'' +
                ", upiId='" + upiId + '\'' +
                ", desc='" + desc + '\'' +
                '}';
    }
}
